### PR TITLE
Cache charmcraft pack container, skip unstable tests except on schedule

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**
Ported from https://github.com/canonical/mysql-k8s-operator/pull/146

### CODE REVIEW

**Comment by averma-canonical** [comment]
Thanks @carlcsaposs-canonical, actually this is the Spark History Server component. The problematic integration tests are for Spark itself which are in the [spark-client](https://github.com/canonical/spark-client-snap) repo.

Also, I believe you are proposing to exclude integration tests during PRs. I think this needs to be revisited. I am [adding 2 hr timeout](https://github.com/canonical/spark-client-snap/pull/37) to the spark integration tests which might help.

Let's discuss when you have some time.

cc: @deusebio, @taurus-forever

**Comment by taurus-forever** [comment]
As Carl mentioned, the PR is to speedup building of your charm by caching and restoring LXD for charmcraft:

> Build charms / Collect charms (pull_request) Successful in 9s
> Tests / integration (pull_request) Successful in 7m

No tests should be skipped here. Up to BigData team to merge or close PR. JFYI:

CI without caching: [14 mins](https://github.com/canonical/spark-history-server-k8s-operator/actions/runs/4173332168)
CI with caching: [10 mins](https://github.com/canonical/spark-history-server-k8s-operator/actions/runs/4207526776)

**Review by deusebio — APPROVED** [review]
Just the same minor as in s3-integrator, but after looking at the other PR, I believe this makes the UX also a bit more consistent

**Comment by deusebio** [comment]
Oh, I see we have conflicts. I can solve them

**Review by averma-canonical — APPROVED** [review]

**Pull request merged**
